version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  workflow:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Checklist-App/server/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
          
jobs:
  pull_and_start:
    executor: workflow
    steps:
      - checkout
      - node/install
      - run: 
          name: Install Dependencies
          command: npm install
      - run: 
          name: Generate Bank
          command: npx prisma generate dev
      - run:
          name: Build
          command: npm run build         

workflows:
  my-custom-workflow:
    jobs:
      - pull_and_start

