version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Checklist-App/server/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  pull_and_start:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm i
          npx prisma generate dev
          npm run build
          npm run start

workflows:
  my-custom-workflow:
    jobs:
      - pull_and_start

