version: 2.1
orbs:
  node: circleci/node@5.1.0
executors:
  create_docker:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
  docker_ssh:
     docker:
       - image: arvindr226/alpine-ssh
          
jobs:
  pull:
    executor: create_docker
    steps:
      - checkout
      - node/install
      - run: 
          name: Install Dependencies
          command: npm install
      - run: 
          name: Generate Bank
          command: npx prisma generate dev
      - run:
          name: Build
          command: npm run build
      - run:
          name: Prepar files for transfer
          command: |
            mkdir deploy
            cp -r ./prisma ./build ./package.json deploy/ 
      - run:
          name: Transfer files to server
          command: scp -o StrictHostKeyChecking=no -r ./deploy circleci@64.225.6.102:/home/circleci/www/checklist-api.smartnewservices.com.br
      - run:
          name: Execute deployment commands on server
          command: ssh -o StrictHostKeyChecking=no -v circleci@64.225.6.102 "cd /home/circleci/www/checklist-api.smartnewservices.com.br && npm install && < /dev/null"
      
  deploy:
     executor: docker_ssh
     steps: 
       - checkout
       - run:
          name: APK UPDATE
          command: apk update
       - run:
          name: APK Search
          command: apk search curl
       - run:
          name: Install curl
          command: apk add curl
       - run:
          name: Install NVM
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
       - run:
          name: NVM V16
          command: nvm install v16 && nvm use v16        
       - run: ssh -oStrictHostKeyChecking=no -v circleci@64.225.6.102 "./checklist-api.sh"

workflows:
  workflow:
    jobs:
      - pull:
          filters:
            branches:
              only:
                - master

