name: Build & Deploy to SFTP on push

on:
  push:
    branches:
      - master

jobs:
  deploy-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
          yarn-cache-folder: ~/.cache/yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Build
        run: yarn build

      - name: Combine build and package.json
        run: |
          mkdir combined
          cp -R ./build/* ./combined
          cp ./package.json ./combined
          cp -R ./prisma ./combined

      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: /home/checklistappapi/public_html/
          local_path: ./combined/*
          port: 22022

      - name: Install Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load nvm
          nvm install v16.15.1

      - name: SSH + Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 22022
          username: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nvm use v16.15.1
            cd /home/checklistappapi/public_html/
            yarn
            yarn prisma generate
            pm2 restart checklistappapi